# Generated by Django 3.1.7 on 2021-03-29 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
    ]
