# Generated by Django 3.1.7 on 2021-04-02 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20210331_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='engineer',
        ),
    ]
