# Generated by Django 3.1.7 on 2021-04-02 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210401_2346'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
