# Generated by Django 3.2 on 2021-04-09 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department_name',
            field=models.CharField(choices=[('TPG', 'Tooling Products'), ('AE', 'Application Engineering'), ('ME', 'Machine Engineering'), ('MA', 'Manufacturing & Assembly')], max_length=100),
        ),
    ]
