# Generated by Django 3.2 on 2021-04-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_department_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department_name',
            field=models.CharField(choices=[('Tooling Products', 'Tooling Products'), ('Application Engineering', 'Application Engineering'), ('Machine Engineering', 'Machine Engineering'), ('Manufacturing & Assembly', 'Manufacturing & Assembly')], max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_number',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
